server:
  port: ${PORT:8761}
spring:
  application:
    name: eurekaserver
eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

    
    
    